####
# This file controls how Terrateam orchestrates your Terraform code.
# Below, we define:
# 1. Basic dir -> tag associations (staging, production).
# 2. Basic workflows for each environment.
# 3. Hooks for pre/post plan or apply steps.
# 4. Optional advanced sections for OIDC, advanced RBAC, config builder, etc.
####
# This configuration does not contain all of the Terrateam configuration
# options. The purpose of this file is to showcase how Terrateam can be
# configured to orchestrate your Terraform operations. Terrateam can fit into
# any monorepo by leveraging a combination of workflowss and tag queries.
# Need help? Ping us on Slack: https://terrateam.io/slack or support@terrateam.io
# Docs: https://docs.terrateam.io
####

################################################################################
# Directories (dirs)
# Define logical groupings of Terraform configurations.
# Tags allow dynamic selection of directories (e.g., "staging" and "compute")
################################################################################
dirs:
  staging/compute:
    when_modified:
      file_patterns: ["${DIR}/*.tf", "../modules/*.tf"]
    tags: ["staging", "compute"]
  production/compute:
    when_modified:
      file_patterns: ["${DIR}/*.tf", "../modules/*.tf"]
    tags: ["production", "compute"]
  modules:
    when_modified: [] # Don't run Terrateam inside the modules directory
  # If you add more directories (like "dev/compute"), place them here with tags.
